### ISSUE TITLE
USER STORY: Landing page

### ISSUE THREAD

**Issue by CeciliaSwe** [CeciliaSwe/portfolio-5th#1]
As a first time user I can see a landing page so that I can understand what shop sells and to be encouraged to make a purchase

## Tasks
- [x] basic layout of landing page
- [x] link to products
- [x] Real text and links in 3 info boxes instead of Lorem Ipsum
